Browser session UI
matrix-org/matrix-authentication-service pull request #1616
Opened 2023-08-28 01:49 UTC by kerryarchibald

Fixes https://github.com/matrix-org/matrix-authentication-service/issues/1545

Use the same generic session element for browser sessions

<img width="524" alt="Screenshot 2023-08-28 at 13 47 53" src="https://github.com/matrix-org/matrix-authentication-service/assets/3055605/61d2df61-ae84-4942-82f2-c9689225a6ec">

2023-08-28 08:38 UTC, sandhose requested changes
Just a leftover class in the CSS module, otherwise LGTM

2023-08-28 08:38 UTC, sandhose commented on frontend/src/components/UserHome/UserHome.tsx
> -      <section className={styles.sessionList}>
That class is still in the CSS module

2023-08-28 23:51 UTC, kerryarchibald commented
Thanks @sandhose
I've enabled auto-merge

2023-08-29 00:07 UTC, merged

2023-08-29 02:11 UTC, kerryarchibald commented
Oops, didn't realise it would merge without approval.