Document the admin API
matrix-org/matrix-authentication-service pull request #3038
Opened 2024-07-31 16:30 UTC by sandhose

This is on top of a merge of all the current admin API PRs, hence the draft status.

This documents the admin API, explaining how to use it, and links to the OpenAPI spec, as well as Swagger UI.

Fixes #2604
Fixes 2239

2024-08-02 09:56 UTC, hughns requested changes
As per conversation this morning, we should clarify that the GraphQL API is now intended for internal (to MAS) usage only.

2024-08-02 09:56 UTC, hughns commented on docs/SUMMARY.md
>  - [GraphQL API](./reference/graphql.md)
We should rename the GraphQL API to be Internal GraphQL API. Some things to do:

- Move the existing GraphQL API documentation into the Development section of the documentation hierachy.
- Change all references to "GraphQL API" in the documentation to "Internal GraphQL API".
- Add a callout section at the top of the Internal GraphQL API documentation to say:
  - This API is now for internal use only
  - External usage is now deprecated and will be blocked/removed in a future release
  - The new Admin API should be used instead

2024-08-02 09:56 UTC, hughns commented on docs/reference/scopes.md
The `urn:mas:graphql:*` section should reference the Internal GraphQL API and make it clear that this is for internal (to MAS) usage only.

2024-08-02 13:11 UTC, hughns commented on docs/SUMMARY.md
>  - [GraphQL API](./reference/graphql.md)
I've done this myself.

2024-08-02 13:11 UTC, hughns commented on docs/reference/scopes.md
I've dene this myself.

2024-08-06 10:06 UTC, sandhose commented
I rebased it on top of main instead of the merge of all pending APIs, so that this can get merged without depending on the rest

2024-08-07 15:41 UTC, merged