Make PKCE implementation compliant with RFC7636
matrix-org/matrix-authentication-service pull request #320
Opened 2022-08-01 18:20 UTC by sandhose

This checks for the PKCE code_verifier length as well as the characters
used. It also give better errors when the PKCE verifier is invalid.

Fixes #316

2022-08-01 18:22 UTC, sandhose commented on crates/data-model/src/oauth2/authorization_grant.rs
> +    #[error("code_verifier should be at least 43 characters long")]
So here the `error_description` would look like that:

```
PKCE verification failed: code_verifier should be at least 43 characters long
```

2022-08-02 11:43 UTC, hughns requested changes
Condition for max length is wrong. Otherwise looks good.

2022-08-02 11:43 UTC, hughns commented on crates/data-model/src/oauth2/authorization_grant.rs
> +        if verifier.len() > 43 {
```suggestion
        if verifier.len() > 128 {
```

2022-08-02 13:25 UTC, sandhose commented
Actually the allowed characters check was also buggy. Fixed it and added a bunch of unit tests

2022-08-03 11:53 UTC, hughns approved these changes

2022-08-03 11:57 UTC, merged